### ISSUE TITLE
about some code in tools/ron/generate_derpn_labels_targets_layer.py/self.eval_obs_region(gt_boxes)

### ISSUE THREAD

**Issue by ztyxd** [HCIILAB/DeRPN#3]
def eval_obs_region(self, gt_boxes):
            height, width = self.height, self.width
            observe_region = np.zeros((height, width), np.int32)
            scaled_gt = gt_boxes[:,:4].copy()/float(self._feat_stride)#gt scaled to featrue map
            gt_w = scaled_gt[:, 2] -scaled_gt[:, 0]
            gt_h = scaled_gt[:, 3] -scaled_gt[:, 1]
            gt_cx = (scaled_gt[:, 2] + scaled_gt[:, 0])*0.5
            gt_cy = (scaled_gt[:, 3] + scaled_gt[:, 1])*0.5

            start_x = np.maximum((gt_cx - gt_w*self.extend_ratio*0.5).astype(np.int32), 0)
            end_x = np.minimum((gt_cx + gt_w*self.extend_ratio*0.5).astype(np.int32), width-1)
            start_y = np.maximum((gt_cy - gt_h*self.extend_ratio*0.5).astype(np.int32), 0)
            end_y = np.minimum((gt_cy + gt_h*self.extend_ratio*0.5).astype(np.int32), height-1)
            for ith in range(gt_boxes.shape[0]):                
                observe_region[start_y[ith]:end_y[ith]+1,start_x[ith]:end_x[ith]+1] = 1
            return observe_region, gt_cx, gt_cy`
`
The function of the above code, i think it is to reflect the gtbox into the feature map, and start_x,end_x ,start_y and end_y is to compute the coordinate in the feature map.
But what does the self.extend-ratio mean and why it is equal to 1.2?
And maybe i dismiss the real function of the above codes.
thanks a lo

**Comment by Lele-Xie** [comment]
The DeRPN needs to observe the predicted results and then assigns the labels. We can only observe the effective regions  to speed up this procedure. The extend_ratio is used to determine the effective regions around the ground truths and extending the GT by 1.2 is enough to cover most latent positive labels.

**Comment by ztyxd** [comment]
thank you very much
But I don't think it seems to mention this in the paper.
When I look at the source code.The DeRPN is quite different from the traditional RPN when generating the anchor. These seem to be not explained in the paper.

**Comment by Lele-Xie** [comment]
Hello~
We cannot present every implementation detail in the paper as the space is really limited. Nevertheless, the methodology of this paper has been explained clearly enough.

**Comment by ztyxd** [comment]
Thanks a lot. It is really a good work.
